### PR TITLE
🧭 Refactor User and Session Management

### PR DESCRIPTION
**Pull request by shrihari689**
### Changes Made

- Split New User Creation (Superuser) workflow and Sign Up workflow. Reason behind this is New User Creation page redirects to signup/signin page.

- Because of this, changed signup routes.

- Update the new routes in all templates.

- Refactor all tests (linked to these changes).

- Add Respective Flash Error and Notice messages. (like Logout, New User added)

| Switch on to this branch on the editor to review these things would be easy.

### CODE REVIEW

**Comment by arnabsen1729** [comment]
I would love to hear other's opinions as well. Cause signup is nothing but a creation of a user. Whereas sign-in is just the creation of a new session. So, we are dealing with two different models here. Like session#new is in turn creating a new user, might get confusing in future. 

Although the flash messages are a really good addition and there were no breaking changes as far as I noticed.

**Comment by shrihari689** [comment]
>  ## Yeah! I would like hear all others opinion too. 🎉 

I am too confused here. But these things were in mind when I made these changes.

- Idea behind the change is that, maybe at some cases in future we don't have same logic for `New User Creation by Superuser` and `Sign Up`, (including redirecting to Sign In / Sign Up , "Sign Up Successful" messages on successful `New User Creation by Superuser` operation) 💣

- If it is separate, we can also filter that when signing up, the user selects only the `User::SIGNUP_ROLES` 🔍

- another thing would be like `session#new` and all names that are confusing could renamed as well with respective controller functions. (like `sessions/sign_up`, `sessions/sign_in`, `sessions#sign_up`, `sessions#sign_up_view`) 💡

- also I think both `sign_in` and `sign_up` operations are dependent of User model. Which is basically a **read** operation for `sign_in` and **write** operation for `sign_up` 🤔

- the last question came to mind, when a superuser create a user, will it should be `verified` or again the superuser should verify them by going to Users Dashboard? 🤯

**Comment by arnabsen1729** [comment]
To answer your last question, when the users are created by superuser they will be verified. Only those who signs up have to be verified manually

**Comment by shrihari689** [comment]
Then we have two different logics, right? 🤔 which means they need to separated?

**Comment by bodhish** [comment]
> Then we have two different logics, right? 🤔
> I think currently, we are creating both users with `verified: false`

The right approach is to make the default value for `verified: false`, this way we can explicitly set the verified flag via specific actions.

**Review by khavinshankar — APPROVED** [review]

**Comment by shrihari689** [comment]
Yeah @bodhish ! 🎉
That would be great idea 💡

**Review by arnabsen1729 — APPROVED** [review]

**Comment by shrihari689** [comment]
Closing this now in favor of #44 ! 🚀
Will be back with 🔥

**Pull request closed without merging**
